
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;


public class HuerfanosVisual extends javax.swing.JFrame {

    /**
     * Creates new form huerfanosVisual
     */
    public HuerfanosVisual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHuerfanos = new javax.swing.JTable();
        txtIdentificación = new javax.swing.JLabel();
        txtIdentificacionHuerfano = new javax.swing.JTextField();
        txtNombreHuerfano = new javax.swing.JTextField();
        txtIdentificación1 = new javax.swing.JLabel();
        txtEdadHuerfano = new javax.swing.JTextField();
        txtIdentificación2 = new javax.swing.JLabel();
        txtIdentificación3 = new javax.swing.JLabel();
        btnGuardarHuerfano = new javax.swing.JButton();
        btnActualizarHuerfano = new javax.swing.JButton();
        btnEliminarHuerfano = new javax.swing.JButton();
        btnLimpiarCampos = new javax.swing.JButton();
        btnBuscarHuerfano = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtIdentificación4 = new javax.swing.JLabel();
        txtIdentificación5 = new javax.swing.JLabel();
        txtIdentificación6 = new javax.swing.JLabel();
        txtIdentificación7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAdopcion = new javax.swing.JTable();
        txtNombreAdopcion = new javax.swing.JTextField();
        txtTelefonoAdopcion = new javax.swing.JTextField();
        btnAceptarAdopcion = new javax.swing.JButton();
        btnEliminarAdopcion = new javax.swing.JButton();
        btnBuscarAdopcion = new javax.swing.JButton();
        btnActualizarAdopcion = new javax.swing.JButton();
        btnLimpiarCamposAdopcion = new javax.swing.JButton();
        btnSolicitarAdopcion = new javax.swing.JButton();
        cmbHuerfanos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblHuerfanos.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Identificacion", "Nombre", "Edad"
                }
        ));
        jScrollPane2.setViewportView(tblHuerfanos);

        txtIdentificación.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        txtIdentificación.setText("HUERFANOS");

        txtIdentificacionHuerfano.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        txtNombreHuerfano.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        txtIdentificación1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtIdentificación1.setText("Nombre");

        txtEdadHuerfano.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        txtIdentificación2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtIdentificación2.setText("Edad");

        txtIdentificación3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtIdentificación3.setText("Identificación");

        btnGuardarHuerfano.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGuardarHuerfano.setText("Guardar");

        btnActualizarHuerfano.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnActualizarHuerfano.setText("Actualizar");

        btnEliminarHuerfano.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEliminarHuerfano.setText("Eliminar");

        btnLimpiarCampos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLimpiarCampos.setText("Limpiar campos");

        btnBuscarHuerfano.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBuscarHuerfano.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(55, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(txtIdentificación2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(txtEdadHuerfano, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(txtIdentificación1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(txtNombreHuerfano, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(txtIdentificación3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtIdentificacionHuerfano, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btnGuardarHuerfano)
                                                                        .addComponent(btnBuscarHuerfano, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(45, 45, 45)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(btnActualizarHuerfano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(btnEliminarHuerfano, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(61, 61, 61))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btnLimpiarCampos)
                                                                .addGap(110, 110, 110))))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(299, 299, 299)
                                .addComponent(txtIdentificación)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIdentificación)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtIdentificacionHuerfano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtIdentificación3))
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtIdentificación1)
                                                        .addComponent(txtNombreHuerfano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnGuardarHuerfano, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnEliminarHuerfano, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btnActualizarHuerfano, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnBuscarHuerfano, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtIdentificación2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtEdadHuerfano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jTabbedPane1.addTab("Huerfanos", jPanel1);

        txtIdentificación4.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        txtIdentificación4.setText("ADOPCIONES");

        txtIdentificación5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtIdentificación5.setText("Identificación huerfano");

        txtIdentificación6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtIdentificación6.setText("Telefono contacto");

        txtIdentificación7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtIdentificación7.setText("Nombre solicitante");

        tblAdopcion.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Identificacion huerfano", "Telefono contacto", "Nombre splicitante"
                }
        ));
        jScrollPane3.setViewportView(tblAdopcion);

        txtNombreAdopcion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        txtTelefonoAdopcion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        btnAceptarAdopcion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAceptarAdopcion.setText("Adoptar");

        btnEliminarAdopcion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEliminarAdopcion.setText("Eliminar");

        btnBuscarAdopcion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBuscarAdopcion.setText("Buscar");

        btnActualizarAdopcion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnActualizarAdopcion.setText("Actualizar");

        btnLimpiarCamposAdopcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpiarCamposAdopcion.setText("Liampiar campos");

        btnSolicitarAdopcion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSolicitarAdopcion.setText("Solicitar");

        cmbHuerfanos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbHuerfanos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un huerfano" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(55, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtIdentificación5)
                                                        .addComponent(txtIdentificación7)
                                                        .addComponent(txtIdentificación6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txtNombreAdopcion, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtTelefonoAdopcion, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cmbHuerfanos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(46, 46, 46)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(btnBuscarAdopcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnAceptarAdopcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnLimpiarCamposAdopcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnActualizarAdopcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnEliminarAdopcion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnSolicitarAdopcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(299, 299, 299)
                                .addComponent(txtIdentificación4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtIdentificación4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(txtIdentificación5)
                                                                        .addComponent(cmbHuerfanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(42, 42, 42)
                                                                .addComponent(txtIdentificación6))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(btnAceptarAdopcion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btnEliminarAdopcion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(btnActualizarAdopcion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btnBuscarAdopcion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(17, 17, 17)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnLimpiarCamposAdopcion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnSolicitarAdopcion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtNombreAdopcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtIdentificación7)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addComponent(txtTelefonoAdopcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Adopción", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    public JButton getBtnAceptarAdopcion() {
        return btnAceptarAdopcion;
    }

    public void setBtnAceptarAdopcion(JButton btnAceptarAdopcion) {
        this.btnAceptarAdopcion = btnAceptarAdopcion;
    }

    public JButton getBtnActualizarAdopcion() {
        return btnActualizarAdopcion;
    }

    public void setBtnActualizarAdopcion(JButton btnActualizarAdopcion) {
        this.btnActualizarAdopcion = btnActualizarAdopcion;
    }

    public JButton getBtnActualizarHuerfano() {
        return btnActualizarHuerfano;
    }

    public void setBtnActualizarHuerfano(JButton btnActualizarHuerfano) {
        this.btnActualizarHuerfano = btnActualizarHuerfano;
    }

    public JButton getBtnBuscarAdopcion() {
        return btnBuscarAdopcion;
    }

    public void setBtnBuscarAdopcion(JButton btnBuscarAdopcion) {
        this.btnBuscarAdopcion = btnBuscarAdopcion;
    }

    public JButton getBtnBuscarHuerfano() {
        return btnBuscarHuerfano;
    }

    public void setBtnBuscarHuerfano(JButton btnBuscarHuerfano) {
        this.btnBuscarHuerfano = btnBuscarHuerfano;
    }

    public JButton getBtnEliminarAdopcion() {
        return btnEliminarAdopcion;
    }

    public void setBtnEliminarAdopcion(JButton btnEliminarAdopcion) {
        this.btnEliminarAdopcion = btnEliminarAdopcion;
    }

    public JButton getBtnEliminarHuerfano() {
        return btnEliminarHuerfano;
    }

    public void setBtnEliminarHuerfano(JButton btnEliminarHuerfano) {
        this.btnEliminarHuerfano = btnEliminarHuerfano;
    }

    public JButton getBtnGuardarHuerfano() {
        return btnGuardarHuerfano;
    }

    public void setBtnGuardarHuerfano(JButton btnGuardarHuerfano) {
        this.btnGuardarHuerfano = btnGuardarHuerfano;
    }

    public JButton getBtnLimpiarCampos() {
        return btnLimpiarCampos;
    }

    public void setBtnLimpiarCampos(JButton btnLimpiarCampos) {
        this.btnLimpiarCampos = btnLimpiarCampos;
    }

    public JButton getBtnLimpiarCamposAdopcion() {
        return btnLimpiarCamposAdopcion;
    }

    public void setBtnLimpiarCamposAdopcion(JButton btnLimpiarCamposAdopcion) {
        this.btnLimpiarCamposAdopcion = btnLimpiarCamposAdopcion;
    }

    public JButton getBtnSolicitarAdopcion() {
        return btnSolicitarAdopcion;
    }

    public void setBtnSolicitarAdopcion(JButton btnSolicitarAdopcion) {
        this.btnSolicitarAdopcion = btnSolicitarAdopcion;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JTable getTblAdopcion() {
        return tblAdopcion;
    }

    public void setTblAdopcion(JTable tblAdopcion) {
        this.tblAdopcion = tblAdopcion;
    }

    public JTable getTblHuerfanos() {
        return tblHuerfanos;
    }

    public void setTblHuerfanos(JTable tblHuerfanos) {
        this.tblHuerfanos = tblHuerfanos;
    }

    public JTextField getTxtEdadHuerfano() {
        return txtEdadHuerfano;
    }

    public void setTxtEdadHuerfano(JTextField txtEdadHuerfano) {
        this.txtEdadHuerfano = txtEdadHuerfano;
    }

    public JComboBox<String> getCmbHuerfanos() {
        return cmbHuerfanos;
    }

    public void setCmbHuerfanos(JComboBox<String> cmbHuerfanos) {
        this.cmbHuerfanos = cmbHuerfanos;
    }


    public JTextField getTxtIdentificacionHuerfano() {
        return txtIdentificacionHuerfano;
    }

    public void setTxtIdentificacionHuerfano(JTextField txtIdentificacionHuerfano) {
        this.txtIdentificacionHuerfano = txtIdentificacionHuerfano;
    }

    public JLabel getTxtIdentificación() {
        return txtIdentificación;
    }

    public void setTxtIdentificación(JLabel txtIdentificación) {
        this.txtIdentificación = txtIdentificación;
    }

    public JLabel getTxtIdentificación1() {
        return txtIdentificación1;
    }

    public void setTxtIdentificación1(JLabel txtIdentificación1) {
        this.txtIdentificación1 = txtIdentificación1;
    }

    public JLabel getTxtIdentificación2() {
        return txtIdentificación2;
    }

    public void setTxtIdentificación2(JLabel txtIdentificación2) {
        this.txtIdentificación2 = txtIdentificación2;
    }

    public JLabel getTxtIdentificación3() {
        return txtIdentificación3;
    }

    public void setTxtIdentificación3(JLabel txtIdentificación3) {
        this.txtIdentificación3 = txtIdentificación3;
    }

    public JLabel getTxtIdentificación4() {
        return txtIdentificación4;
    }

    public void setTxtIdentificación4(JLabel txtIdentificación4) {
        this.txtIdentificación4 = txtIdentificación4;
    }

    public JLabel getTxtIdentificación5() {
        return txtIdentificación5;
    }

    public void setTxtIdentificación5(JLabel txtIdentificación5) {
        this.txtIdentificación5 = txtIdentificación5;
    }

    public JLabel getTxtIdentificación6() {
        return txtIdentificación6;
    }

    public void setTxtIdentificación6(JLabel txtIdentificación6) {
        this.txtIdentificación6 = txtIdentificación6;
    }

    public JLabel getTxtIdentificación7() {
        return txtIdentificación7;
    }

    public void setTxtIdentificación7(JLabel txtIdentificación7) {
        this.txtIdentificación7 = txtIdentificación7;
    }

    public JTextField getTxtNombreAdopcion() {
        return txtNombreAdopcion;
    }

    public void setTxtNombreAdopcion(JTextField txtNombreAdopcion) {
        this.txtNombreAdopcion = txtNombreAdopcion;
    }

    public JTextField getTxtNombreHuerfano() {
        return txtNombreHuerfano;
    }

    public void setTxtNombreHuerfano(JTextField txtNombreHuerfano) {
        this.txtNombreHuerfano = txtNombreHuerfano;
    }

    public JTextField getTxtTelefonoAdopcion() {
        return txtTelefonoAdopcion;
    }

    public void setTxtTelefonoAdopcion(JTextField txtTelefonoAdopcion) {
        this.txtTelefonoAdopcion = txtTelefonoAdopcion;
    }




    // Variables declaration - do not modify
    private javax.swing.JButton btnAceptarAdopcion;
    private javax.swing.JButton btnActualizarAdopcion;
    private javax.swing.JButton btnActualizarHuerfano;
    private javax.swing.JButton btnBuscarAdopcion;
    private javax.swing.JButton btnBuscarHuerfano;
    private javax.swing.JButton btnEliminarAdopcion;
    private javax.swing.JButton btnEliminarHuerfano;
    private javax.swing.JButton btnGuardarHuerfano;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnLimpiarCamposAdopcion;
    private javax.swing.JButton btnSolicitarAdopcion;
    private javax.swing.JComboBox<String> cmbHuerfanos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblAdopcion;
    private javax.swing.JTable tblHuerfanos;
    private javax.swing.JTextField txtEdadHuerfano;
    private javax.swing.JTextField txtIdentificacionHuerfano;
    private javax.swing.JLabel txtIdentificación;
    private javax.swing.JLabel txtIdentificación1;
    private javax.swing.JLabel txtIdentificación2;
    private javax.swing.JLabel txtIdentificación3;
    private javax.swing.JLabel txtIdentificación4;
    private javax.swing.JLabel txtIdentificación5;
    private javax.swing.JLabel txtIdentificación6;
    private javax.swing.JLabel txtIdentificación7;
    private javax.swing.JTextField txtNombreAdopcion;
    private javax.swing.JTextField txtNombreHuerfano;
    private javax.swing.JTextField txtTelefonoAdopcion;
    // End of variables declaration
}
